### ISSUE TITLE
svg with no labels

### ISSUE THREAD

**Issue by MDSharma** [cobilab/smash#5]
Hi, the output svg does not seem to have labels associated with the drawings. Is there a way to know which drawing belongs to the ref or query?

**Comment by pratas** [comment]
Dear Sharma,

if you use:  ./SMASH A B

A -> first map;
B -> second map.

For enhanced use of smash, see smash++: https://github.com/smortezah/smashpp

which draws labels and uses high sensitivity (besides other features).
