### ISSUE TITLE
Warning: file (null) was not deleted.

### ISSUE THREAD

**Issue by Karimi-81** [cobilab/smash#7]
I faced with the following error when comparing two large mammalian genomes:
Warning: file (null) was not deleted.
the command was:
./SMASH pseudo_dog10.fa pseudo_cat10.fa
do you have any idea about this error and how can I handle such analysis using smash?
Thanks.

**Comment by pratas** [comment]
Dear,

this is a warning that will not affect the run. Basically, the file and permissions are not checked.
Nevertheless, an optimized version of smash is available: smash++ (https://github.com/smortezah/smashpp)

Best regards,
Diogo
